"""fix

Revision ID: 087b246e1558
Revises: 8f1ccaf5d4d9
Create Date: 2023-03-14 13:19:45.067184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087b246e1558'
down_revision = '8f1ccaf5d4d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outstanding_tokens_jti', table_name='outstanding_tokens')
    op.create_index(op.f('ix_outstanding_tokens_jti'), 'outstanding_tokens', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outstanding_tokens_jti'), table_name='outstanding_tokens')
    op.create_index('ix_outstanding_tokens_jti', 'outstanding_tokens', ['jti'], unique=False)
    # ### end Alembic commands ###
