"""user_id

Revision ID: 8f1ccaf5d4d9
Revises: ea9aaef4d774
Create Date: 2023-03-13 14:06:20.928681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1ccaf5d4d9'
down_revision = 'ea9aaef4d774'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outstanding_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outstanding_tokens', 'user_id')
    # ### end Alembic commands ###
