"""tokens

Revision ID: ea9aaef4d774
Revises: 91926cceeffe
Create Date: 2023-03-13 10:10:02.246882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9aaef4d774'
down_revision = '91926cceeffe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outstanding_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outstanding_tokens_id'), 'outstanding_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_outstanding_tokens_jti'), 'outstanding_tokens', ['jti'], unique=True)
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outstanding_token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['outstanding_token_id'], ['outstanding_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_tokens_id'), 'blacklist_tokens', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_blacklist_tokens_id'), table_name='blacklist_tokens')
    op.drop_table('blacklist_tokens')
    op.drop_index(op.f('ix_outstanding_tokens_jti'), table_name='outstanding_tokens')
    op.drop_index(op.f('ix_outstanding_tokens_id'), table_name='outstanding_tokens')
    op.drop_table('outstanding_tokens')
    # ### end Alembic commands ###
